### PR TITLE
8.2 Build and Distribution Readiness

### PR DESCRIPTION
**Pull request by timothystone**
As I was preparing to submit this to NetBeans plugins, I found your fork.

This will build the 8.2 module with your work. Additionally, it prepares the plugin for distribution, credits Diego as the author, links to his parent fork, and readies the project to build directly in NetBeans.

To distribute, one must create a signing keystore, [documented here on the NB Wiki](http://wiki.netbeans.org/DevFaqSignNbm#How_can_I_sign_Maven_based_NBMs_I_create.3F). I was about to do this when I realized that maybe you should own that as the most recent meaningful work was performed by you.

The command to build and sign is: 

```shell
mvn clean package nbm:nbm \
-Dkeystorepass=<strong-password> \
-Dkeystore=nbproject/private/keystore \
-Dkeystorealias=<alias>
```

Hope this helps!

### CODE REVIEW

**Comment by Chris2011** [comment]
Thx, I will have a look into it later. Atm there are some problem with this plugin. Here you can see the issues: https://github.com/dzsessona/Cetriolo/issues/31 (Scanning for feature files) but I don't know why this is needed. I wanted to remove this scan but didn't have time yet. Would be great, if you can have a look into it and maybe comment this feature out or find a better solution.

The other problem is, the lexer needs some fixes. for ignoring parsing or smth like that. If you open a feature and there is a string at the end you and start to remove single characters from the end for the file, I got an exception.

So I will bring it with a new name to NetBeans, because this is a really missing feature, but I don't have time atm to fix those problems which are big enough to bring it not as a new plugin. So any help is appreciated :)


Regards

Chris

P.s. this will not affect this PR, I will look into it when I have time or I will fix it by my own, because, I think I did it, but it is only on my local machine.

**Comment by timothystone** [comment]
I have not seen this problem in NB 8.2. Since the project is currently expecting 7.4, could it be that this is fixed? 

Steps to reproduce?

**Comment by Chris2011** [comment]
The scanning is not a bug, it is an implemented feature but it is a pain in the ass, it will often scan for feature files, after opening java projects and in other cases. I will try to reproduce it again.

The bug of the lexer, I will test it again and will give steps to reproduce, it could be that the problem was because of my refactoring.

**Comment by Chris2011** [comment]
This is the official bug: https://github.com/dzsessona/Cetriolo/issues/23

Create a new file -> Cucumber -> a more complex feature. When you set the cursor to the end of the file and try to delete character by character you got an IlligalStateException:

```gherkin
      Examples:
         | belt level| opponent    | expected action    |
         | third     | a samurai   | engage the opponent|
         | third     | Chuck Norris| run for his life   |
```

so try to delete from EOF. It only happens, if the third example is the last line.

**Comment by Chris2011** [comment]
So the lexer needs some fixes for this handling.

**Comment by timothystone** [comment]
Checking now. I have some freaky feature files I can test with right now...

**Comment by Chris2011** [comment]
I will try to fix the lexer or I will ask someone who can fix it. I got a similar Problem with my C# lexer.

**Comment by timothystone** [comment]
i see it.

The Lexer is hosed. I think the foldinfo range is messed up somehow. In all my feature files, the first issue is the `Feature:` keyword fails as missing a title. This corrects itself just by touching the line. Then the Parser error comes back with the offset moving to the `Background:` keyword. Only this is the end, not the beginning. 

The problem could be in the findEnd and findBeginning methods.

**Comment by Chris2011** [comment]
I don't know much about feature files yet, so I can't say, whether this is "correct" somehow or not, that there is a title missing and whether there is the correct place where it shows the error.

**Comment by Chris2011** [comment]
Anyway, we should create more issues to capture those misbehaviour. Only wanted that you know the problems before we can release it again. :). What you've found, could be another problem.

**Comment by timothystone** [comment]
I think they are related. I see the IllegalStateException described in dzsessona#23, but it's not inhibiting my IDE. The scans complete. 

The ability of the Feature file to use code folding appears to be the root cause of the described issue.

**Comment by timothystone** [comment]
And I'm refactoring some misspellings littered throughout the project. I should probably branch this. :)

**Comment by Chris2011** [comment]
Thx for your help. I started some months ago but I don't know much about lexer and antlr and so on, so I only changed the icons and wanted to prevent the scanning. Great to see there is still some interest in it and I think it will be more, if we have a stable version to use. I will add the generation of the keystore file to the pom file too, to make it automatic while building.

**Comment by Chris2011** [comment]
Btw, join our NetBeans slack chan :) we can talk there about more details. https://netbeans.signup.team

**Comment by Chris2011** [comment]
I got an answer from a developer who helped with the C# lexer, he gave me some hints. I will translate it in english and will post it here.

**Comment by Chris2011** [comment]
Here is the answer:

```
Hi Chris,

The UNKNOWN_CHAR should definitely be added as the last token in the lexer. The error you described is more like the one of the UNTERMINATED_STRING. You expect at T_ROW a token as a whole line including a closing pipe. Same with PHOLDER and DOCSTR. You should only define individual tokens and no rules in the lexer. That should happen in the parser. Then it works with the error handling.

Example for the replacement of T_ROW:
Under "Lexer rules":
PIPE: '|'
CELL_CONTENT: (~ ('|' | '\ n' | '\ r')) *
Under "Parser rules" you can then use the tokens in the new rule t_row:
t_row: PIPE (CELL_CONTENT PIPE) + NL
(Originally, your rule also contained ('' | '\ t') *. That is unnecessary now. Whitespaces are automatically hidden by your token WS in the channel HIDDEN and so do not appear in the parser anymore. Simplifies the writing of parser rules.)
Similarly, you must proceed for all your other tokens that can be closed.
```

**Comment by Chris2011** [comment]
@timothystone hey, are you willing to work on it again? The main repo (Cetriolo) has a new owner.

**Pull request merged**
